// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/chaosring.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KVNode_Put_FullMethodName         = "/chaosring.KVNode/Put"
	KVNode_Get_FullMethodName         = "/chaosring.KVNode/Get"
	KVNode_Delete_FullMethodName      = "/chaosring.KVNode/Delete"
	KVNode_ListKeys_FullMethodName    = "/chaosring.KVNode/ListKeys"
	KVNode_StageCopy_FullMethodName   = "/chaosring.KVNode/StageCopy"
	KVNode_Promote_FullMethodName     = "/chaosring.KVNode/Promote"
	KVNode_DropStaging_FullMethodName = "/chaosring.KVNode/DropStaging"
	KVNode_PurgeKeys_FullMethodName   = "/chaosring.KVNode/PurgeKeys"
	KVNode_Fail_FullMethodName        = "/chaosring.KVNode/Fail"
	KVNode_Recover_FullMethodName     = "/chaosring.KVNode/Recover"
	KVNode_Stats_FullMethodName       = "/chaosring.KVNode/Stats"
	KVNode_Handshake_FullMethodName   = "/chaosring.KVNode/Handshake"
)

// KVNodeClient is the client API for KVNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ===========================================================================
// KVNode: 本地键值节点 gRPC 接口
// 每个节点保存本地 KV(含 staging 暂存区), 由路由器远程调用。
// 节点不是自组网成员: 必须先由管理员注册并拿到节点令牌, 否则一律拒绝。
// ===========================================================================
type KVNodeClient interface {
	// 常规读写。走 active ring 时访问正式 map; 迁移期间路由仍指向旧主。
	Put(ctx context.Context, in *NodePutRequest, opts ...grpc.CallOption) (*NodePutResponse, error)
	Get(ctx context.Context, in *NodeGetRequest, opts ...grpc.CallOption) (*NodeGetResponse, error)
	Delete(ctx context.Context, in *NodeDeleteRequest, opts ...grpc.CallOption) (*NodeDeleteResponse, error)
	ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error)
	// 迁移复制: 写入目标节点的 staging 暂存区(不进入正式 map)。
	// 幂等: 同一 (migration_id, key) 重复复制结果一致, 可断点续传。
	StageCopy(ctx context.Context, in *StageCopyRequest, opts ...grpc.CallOption) (*StageCopyResponse, error)
	// 提交切换: 把本节点承担的 staging 条目一次性提升为正式数据。
	// 这一步与"复制完成"严格分离: 复制完不算切换, 必须显式 commit。
	Promote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error)
	// 迁移放弃/旧环退役: 清理本节点上暂存或某旧环遗留的本地副本。
	DropStaging(ctx context.Context, in *DropStagingRequest, opts ...grpc.CallOption) (*DropStagingResponse, error)
	// 旧环退役后, 显式清除本节点上已迁走键的本地副本(不写墓碑, 纯空间回收)。
	PurgeKeys(ctx context.Context, in *PurgeKeysRequest, opts ...grpc.CallOption) (*PurgeKeysResponse, error)
	// 故障注入(仅教学演示): 后续所有调用返回 UNAVAILABLE, 模拟节点宕机。
	Fail(ctx context.Context, in *FailRequest, opts ...grpc.CallOption) (*FailResponse, error)
	Recover(ctx context.Context, in *RecoverRequest, opts ...grpc.CallOption) (*RecoverResponse, error)
	// 热点统计 / 节点自证身份
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*NodeStats, error)
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
}

type kVNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewKVNodeClient(cc grpc.ClientConnInterface) KVNodeClient {
	return &kVNodeClient{cc}
}

func (c *kVNodeClient) Put(ctx context.Context, in *NodePutRequest, opts ...grpc.CallOption) (*NodePutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodePutResponse)
	err := c.cc.Invoke(ctx, KVNode_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVNodeClient) Get(ctx context.Context, in *NodeGetRequest, opts ...grpc.CallOption) (*NodeGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeGetResponse)
	err := c.cc.Invoke(ctx, KVNode_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVNodeClient) Delete(ctx context.Context, in *NodeDeleteRequest, opts ...grpc.CallOption) (*NodeDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeDeleteResponse)
	err := c.cc.Invoke(ctx, KVNode_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVNodeClient) ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKeysResponse)
	err := c.cc.Invoke(ctx, KVNode_ListKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVNodeClient) StageCopy(ctx context.Context, in *StageCopyRequest, opts ...grpc.CallOption) (*StageCopyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StageCopyResponse)
	err := c.cc.Invoke(ctx, KVNode_StageCopy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVNodeClient) Promote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromoteResponse)
	err := c.cc.Invoke(ctx, KVNode_Promote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVNodeClient) DropStaging(ctx context.Context, in *DropStagingRequest, opts ...grpc.CallOption) (*DropStagingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropStagingResponse)
	err := c.cc.Invoke(ctx, KVNode_DropStaging_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVNodeClient) PurgeKeys(ctx context.Context, in *PurgeKeysRequest, opts ...grpc.CallOption) (*PurgeKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeKeysResponse)
	err := c.cc.Invoke(ctx, KVNode_PurgeKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVNodeClient) Fail(ctx context.Context, in *FailRequest, opts ...grpc.CallOption) (*FailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FailResponse)
	err := c.cc.Invoke(ctx, KVNode_Fail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVNodeClient) Recover(ctx context.Context, in *RecoverRequest, opts ...grpc.CallOption) (*RecoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecoverResponse)
	err := c.cc.Invoke(ctx, KVNode_Recover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVNodeClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*NodeStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStats)
	err := c.cc.Invoke(ctx, KVNode_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVNodeClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, KVNode_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KVNodeServer is the server API for KVNode service.
// All implementations must embed UnimplementedKVNodeServer
// for forward compatibility.
//
// ===========================================================================
// KVNode: 本地键值节点 gRPC 接口
// 每个节点保存本地 KV(含 staging 暂存区), 由路由器远程调用。
// 节点不是自组网成员: 必须先由管理员注册并拿到节点令牌, 否则一律拒绝。
// ===========================================================================
type KVNodeServer interface {
	// 常规读写。走 active ring 时访问正式 map; 迁移期间路由仍指向旧主。
	Put(context.Context, *NodePutRequest) (*NodePutResponse, error)
	Get(context.Context, *NodeGetRequest) (*NodeGetResponse, error)
	Delete(context.Context, *NodeDeleteRequest) (*NodeDeleteResponse, error)
	ListKeys(context.Context, *ListKeysRequest) (*ListKeysResponse, error)
	// 迁移复制: 写入目标节点的 staging 暂存区(不进入正式 map)。
	// 幂等: 同一 (migration_id, key) 重复复制结果一致, 可断点续传。
	StageCopy(context.Context, *StageCopyRequest) (*StageCopyResponse, error)
	// 提交切换: 把本节点承担的 staging 条目一次性提升为正式数据。
	// 这一步与"复制完成"严格分离: 复制完不算切换, 必须显式 commit。
	Promote(context.Context, *PromoteRequest) (*PromoteResponse, error)
	// 迁移放弃/旧环退役: 清理本节点上暂存或某旧环遗留的本地副本。
	DropStaging(context.Context, *DropStagingRequest) (*DropStagingResponse, error)
	// 旧环退役后, 显式清除本节点上已迁走键的本地副本(不写墓碑, 纯空间回收)。
	PurgeKeys(context.Context, *PurgeKeysRequest) (*PurgeKeysResponse, error)
	// 故障注入(仅教学演示): 后续所有调用返回 UNAVAILABLE, 模拟节点宕机。
	Fail(context.Context, *FailRequest) (*FailResponse, error)
	Recover(context.Context, *RecoverRequest) (*RecoverResponse, error)
	// 热点统计 / 节点自证身份
	Stats(context.Context, *StatsRequest) (*NodeStats, error)
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	mustEmbedUnimplementedKVNodeServer()
}

// UnimplementedKVNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKVNodeServer struct{}

func (UnimplementedKVNodeServer) Put(context.Context, *NodePutRequest) (*NodePutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedKVNodeServer) Get(context.Context, *NodeGetRequest) (*NodeGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedKVNodeServer) Delete(context.Context, *NodeDeleteRequest) (*NodeDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedKVNodeServer) ListKeys(context.Context, *ListKeysRequest) (*ListKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListKeys not implemented")
}
func (UnimplementedKVNodeServer) StageCopy(context.Context, *StageCopyRequest) (*StageCopyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StageCopy not implemented")
}
func (UnimplementedKVNodeServer) Promote(context.Context, *PromoteRequest) (*PromoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Promote not implemented")
}
func (UnimplementedKVNodeServer) DropStaging(context.Context, *DropStagingRequest) (*DropStagingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropStaging not implemented")
}
func (UnimplementedKVNodeServer) PurgeKeys(context.Context, *PurgeKeysRequest) (*PurgeKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeKeys not implemented")
}
func (UnimplementedKVNodeServer) Fail(context.Context, *FailRequest) (*FailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fail not implemented")
}
func (UnimplementedKVNodeServer) Recover(context.Context, *RecoverRequest) (*RecoverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recover not implemented")
}
func (UnimplementedKVNodeServer) Stats(context.Context, *StatsRequest) (*NodeStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedKVNodeServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedKVNodeServer) mustEmbedUnimplementedKVNodeServer() {}
func (UnimplementedKVNodeServer) testEmbeddedByValue()                {}

// UnsafeKVNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KVNodeServer will
// result in compilation errors.
type UnsafeKVNodeServer interface {
	mustEmbedUnimplementedKVNodeServer()
}

func RegisterKVNodeServer(s grpc.ServiceRegistrar, srv KVNodeServer) {
	// If the following call pancis, it indicates UnimplementedKVNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KVNode_ServiceDesc, srv)
}

func _KVNode_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodePutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVNodeServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVNode_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVNodeServer).Put(ctx, req.(*NodePutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVNode_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVNodeServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVNode_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVNodeServer).Get(ctx, req.(*NodeGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVNode_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVNodeServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVNode_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVNodeServer).Delete(ctx, req.(*NodeDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVNode_ListKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVNodeServer).ListKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVNode_ListKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVNodeServer).ListKeys(ctx, req.(*ListKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVNode_StageCopy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StageCopyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVNodeServer).StageCopy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVNode_StageCopy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVNodeServer).StageCopy(ctx, req.(*StageCopyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVNode_Promote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVNodeServer).Promote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVNode_Promote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVNodeServer).Promote(ctx, req.(*PromoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVNode_DropStaging_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropStagingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVNodeServer).DropStaging(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVNode_DropStaging_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVNodeServer).DropStaging(ctx, req.(*DropStagingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVNode_PurgeKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVNodeServer).PurgeKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVNode_PurgeKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVNodeServer).PurgeKeys(ctx, req.(*PurgeKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVNode_Fail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVNodeServer).Fail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVNode_Fail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVNodeServer).Fail(ctx, req.(*FailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVNode_Recover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVNodeServer).Recover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVNode_Recover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVNodeServer).Recover(ctx, req.(*RecoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVNode_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVNodeServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVNode_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVNodeServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVNode_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVNodeServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVNode_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVNodeServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KVNode_ServiceDesc is the grpc.ServiceDesc for KVNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KVNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chaosring.KVNode",
	HandlerType: (*KVNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _KVNode_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _KVNode_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _KVNode_Delete_Handler,
		},
		{
			MethodName: "ListKeys",
			Handler:    _KVNode_ListKeys_Handler,
		},
		{
			MethodName: "StageCopy",
			Handler:    _KVNode_StageCopy_Handler,
		},
		{
			MethodName: "Promote",
			Handler:    _KVNode_Promote_Handler,
		},
		{
			MethodName: "DropStaging",
			Handler:    _KVNode_DropStaging_Handler,
		},
		{
			MethodName: "PurgeKeys",
			Handler:    _KVNode_PurgeKeys_Handler,
		},
		{
			MethodName: "Fail",
			Handler:    _KVNode_Fail_Handler,
		},
		{
			MethodName: "Recover",
			Handler:    _KVNode_Recover_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _KVNode_Stats_Handler,
		},
		{
			MethodName: "Handshake",
			Handler:    _KVNode_Handshake_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/chaosring.proto",
}

const (
	Router_Get_FullMethodName               = "/chaosring.Router/Get"
	Router_Put_FullMethodName               = "/chaosring.Router/Put"
	Router_Delete_FullMethodName            = "/chaosring.Router/Delete"
	Router_Route_FullMethodName             = "/chaosring.Router/Route"
	Router_RegisterNode_FullMethodName      = "/chaosring.Router/RegisterNode"
	Router_ListNodes_FullMethodName         = "/chaosring.Router/ListNodes"
	Router_Rebalance_FullMethodName         = "/chaosring.Router/Rebalance"
	Router_StartMigration_FullMethodName    = "/chaosring.Router/StartMigration"
	Router_MigrationProgress_FullMethodName = "/chaosring.Router/MigrationProgress"
	Router_CommitSwitch_FullMethodName      = "/chaosring.Router/CommitSwitch"
	Router_AbortMigration_FullMethodName    = "/chaosring.Router/AbortMigration"
	Router_RetryMigration_FullMethodName    = "/chaosring.Router/RetryMigration"
	Router_RetireOldRing_FullMethodName     = "/chaosring.Router/RetireOldRing"
	Router_KeyDistribution_FullMethodName   = "/chaosring.Router/KeyDistribution"
	Router_HotStats_FullMethodName          = "/chaosring.Router/HotStats"
	Router_RingDiff_FullMethodName          = "/chaosring.Router/RingDiff"
	Router_Resume_FullMethodName            = "/chaosring.Router/Resume"
)

// RouterClient is the client API for Router service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ===========================================================================
// Router: 路由 / 集群管理 / 迁移编排
// ===========================================================================
type RouterClient interface {
	// ---- 数据面: 按 active ring 路由, 迁移期间对在途键双写 ----
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// 在途请求可显式指定它发起时使用的环版本; 旧环在宽限期内仍可解析。
	Route(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error)
	// ---- 集群管理 ----
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*NodeList, error)
	// 权重变化(含 weight=0 摘流) -> 构建新环 + 生成迁移计划, 但不自动切换。
	Rebalance(ctx context.Context, in *RebalanceRequest, opts ...grpc.CallOption) (*MigrationInfo, error)
	// ---- 迁移生命周期: 复制与切换显式分离 ----
	StartMigration(ctx context.Context, in *StartMigrationRequest, opts ...grpc.CallOption) (*MigrationInfo, error)
	MigrationProgress(ctx context.Context, in *MigrationProgressRequest, opts ...grpc.CallOption) (*MigrationInfo, error)
	CommitSwitch(ctx context.Context, in *CommitSwitchRequest, opts ...grpc.CallOption) (*MigrationInfo, error)
	AbortMigration(ctx context.Context, in *AbortMigrationRequest, opts ...grpc.CallOption) (*MigrationInfo, error)
	RetryMigration(ctx context.Context, in *RetryMigrationRequest, opts ...grpc.CallOption) (*MigrationInfo, error)
	RetireOldRing(ctx context.Context, in *RetireRingRequest, opts ...grpc.CallOption) (*RetireRingResponse, error)
	// ---- 教学观测 ----
	KeyDistribution(ctx context.Context, in *DistributionRequest, opts ...grpc.CallOption) (*DistributionResponse, error)
	HotStats(ctx context.Context, in *HotStatsRequest, opts ...grpc.CallOption) (*HotStatsResponse, error)
	// 独立复算两个环之间的路由变化量(对已登记键), 与实际迁移量对照。
	RingDiff(ctx context.Context, in *RingDiffRequest, opts ...grpc.CallOption) (*RingDiffResponse, error)
	// 中断恢复: 重启后扫描迁移状态, 回滚未完成复制, 使系统回到确定状态。
	Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error)
}

type routerClient struct {
	cc grpc.ClientConnInterface
}

func NewRouterClient(cc grpc.ClientConnInterface) RouterClient {
	return &routerClient{cc}
}

func (c *routerClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, Router_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, Router_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, Router_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) Route(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteResponse)
	err := c.cc.Invoke(ctx, Router_Route_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, Router_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*NodeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeList)
	err := c.cc.Invoke(ctx, Router_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) Rebalance(ctx context.Context, in *RebalanceRequest, opts ...grpc.CallOption) (*MigrationInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationInfo)
	err := c.cc.Invoke(ctx, Router_Rebalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) StartMigration(ctx context.Context, in *StartMigrationRequest, opts ...grpc.CallOption) (*MigrationInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationInfo)
	err := c.cc.Invoke(ctx, Router_StartMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) MigrationProgress(ctx context.Context, in *MigrationProgressRequest, opts ...grpc.CallOption) (*MigrationInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationInfo)
	err := c.cc.Invoke(ctx, Router_MigrationProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) CommitSwitch(ctx context.Context, in *CommitSwitchRequest, opts ...grpc.CallOption) (*MigrationInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationInfo)
	err := c.cc.Invoke(ctx, Router_CommitSwitch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) AbortMigration(ctx context.Context, in *AbortMigrationRequest, opts ...grpc.CallOption) (*MigrationInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationInfo)
	err := c.cc.Invoke(ctx, Router_AbortMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) RetryMigration(ctx context.Context, in *RetryMigrationRequest, opts ...grpc.CallOption) (*MigrationInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationInfo)
	err := c.cc.Invoke(ctx, Router_RetryMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) RetireOldRing(ctx context.Context, in *RetireRingRequest, opts ...grpc.CallOption) (*RetireRingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetireRingResponse)
	err := c.cc.Invoke(ctx, Router_RetireOldRing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) KeyDistribution(ctx context.Context, in *DistributionRequest, opts ...grpc.CallOption) (*DistributionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DistributionResponse)
	err := c.cc.Invoke(ctx, Router_KeyDistribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) HotStats(ctx context.Context, in *HotStatsRequest, opts ...grpc.CallOption) (*HotStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HotStatsResponse)
	err := c.cc.Invoke(ctx, Router_HotStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) RingDiff(ctx context.Context, in *RingDiffRequest, opts ...grpc.CallOption) (*RingDiffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RingDiffResponse)
	err := c.cc.Invoke(ctx, Router_RingDiff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeResponse)
	err := c.cc.Invoke(ctx, Router_Resume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterServer is the server API for Router service.
// All implementations must embed UnimplementedRouterServer
// for forward compatibility.
//
// ===========================================================================
// Router: 路由 / 集群管理 / 迁移编排
// ===========================================================================
type RouterServer interface {
	// ---- 数据面: 按 active ring 路由, 迁移期间对在途键双写 ----
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// 在途请求可显式指定它发起时使用的环版本; 旧环在宽限期内仍可解析。
	Route(context.Context, *RouteRequest) (*RouteResponse, error)
	// ---- 集群管理 ----
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	ListNodes(context.Context, *ListNodesRequest) (*NodeList, error)
	// 权重变化(含 weight=0 摘流) -> 构建新环 + 生成迁移计划, 但不自动切换。
	Rebalance(context.Context, *RebalanceRequest) (*MigrationInfo, error)
	// ---- 迁移生命周期: 复制与切换显式分离 ----
	StartMigration(context.Context, *StartMigrationRequest) (*MigrationInfo, error)
	MigrationProgress(context.Context, *MigrationProgressRequest) (*MigrationInfo, error)
	CommitSwitch(context.Context, *CommitSwitchRequest) (*MigrationInfo, error)
	AbortMigration(context.Context, *AbortMigrationRequest) (*MigrationInfo, error)
	RetryMigration(context.Context, *RetryMigrationRequest) (*MigrationInfo, error)
	RetireOldRing(context.Context, *RetireRingRequest) (*RetireRingResponse, error)
	// ---- 教学观测 ----
	KeyDistribution(context.Context, *DistributionRequest) (*DistributionResponse, error)
	HotStats(context.Context, *HotStatsRequest) (*HotStatsResponse, error)
	// 独立复算两个环之间的路由变化量(对已登记键), 与实际迁移量对照。
	RingDiff(context.Context, *RingDiffRequest) (*RingDiffResponse, error)
	// 中断恢复: 重启后扫描迁移状态, 回滚未完成复制, 使系统回到确定状态。
	Resume(context.Context, *ResumeRequest) (*ResumeResponse, error)
	mustEmbedUnimplementedRouterServer()
}

// UnimplementedRouterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouterServer struct{}

func (UnimplementedRouterServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRouterServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedRouterServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedRouterServer) Route(context.Context, *RouteRequest) (*RouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Route not implemented")
}
func (UnimplementedRouterServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedRouterServer) ListNodes(context.Context, *ListNodesRequest) (*NodeList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedRouterServer) Rebalance(context.Context, *RebalanceRequest) (*MigrationInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rebalance not implemented")
}
func (UnimplementedRouterServer) StartMigration(context.Context, *StartMigrationRequest) (*MigrationInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartMigration not implemented")
}
func (UnimplementedRouterServer) MigrationProgress(context.Context, *MigrationProgressRequest) (*MigrationInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MigrationProgress not implemented")
}
func (UnimplementedRouterServer) CommitSwitch(context.Context, *CommitSwitchRequest) (*MigrationInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitSwitch not implemented")
}
func (UnimplementedRouterServer) AbortMigration(context.Context, *AbortMigrationRequest) (*MigrationInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortMigration not implemented")
}
func (UnimplementedRouterServer) RetryMigration(context.Context, *RetryMigrationRequest) (*MigrationInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetryMigration not implemented")
}
func (UnimplementedRouterServer) RetireOldRing(context.Context, *RetireRingRequest) (*RetireRingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetireOldRing not implemented")
}
func (UnimplementedRouterServer) KeyDistribution(context.Context, *DistributionRequest) (*DistributionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeyDistribution not implemented")
}
func (UnimplementedRouterServer) HotStats(context.Context, *HotStatsRequest) (*HotStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HotStats not implemented")
}
func (UnimplementedRouterServer) RingDiff(context.Context, *RingDiffRequest) (*RingDiffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RingDiff not implemented")
}
func (UnimplementedRouterServer) Resume(context.Context, *ResumeRequest) (*ResumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedRouterServer) mustEmbedUnimplementedRouterServer() {}
func (UnimplementedRouterServer) testEmbeddedByValue()                {}

// UnsafeRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouterServer will
// result in compilation errors.
type UnsafeRouterServer interface {
	mustEmbedUnimplementedRouterServer()
}

func RegisterRouterServer(s grpc.ServiceRegistrar, srv RouterServer) {
	// If the following call pancis, it indicates UnimplementedRouterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Router_ServiceDesc, srv)
}

func _Router_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_Route_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Route(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_Route_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Route(ctx, req.(*RouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_Rebalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Rebalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_Rebalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Rebalance(ctx, req.(*RebalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_StartMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).StartMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_StartMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).StartMigration(ctx, req.(*StartMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_MigrationProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).MigrationProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_MigrationProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).MigrationProgress(ctx, req.(*MigrationProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_CommitSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitSwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).CommitSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_CommitSwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).CommitSwitch(ctx, req.(*CommitSwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_AbortMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).AbortMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_AbortMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).AbortMigration(ctx, req.(*AbortMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_RetryMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).RetryMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_RetryMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).RetryMigration(ctx, req.(*RetryMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_RetireOldRing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetireRingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).RetireOldRing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_RetireOldRing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).RetireOldRing(ctx, req.(*RetireRingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_KeyDistribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).KeyDistribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_KeyDistribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).KeyDistribution(ctx, req.(*DistributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_HotStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HotStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).HotStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_HotStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).HotStats(ctx, req.(*HotStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_RingDiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RingDiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).RingDiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_RingDiff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).RingDiff(ctx, req.(*RingDiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_Resume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Resume(ctx, req.(*ResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Router_ServiceDesc is the grpc.ServiceDesc for Router service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Router_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chaosring.Router",
	HandlerType: (*RouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Router_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Router_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Router_Delete_Handler,
		},
		{
			MethodName: "Route",
			Handler:    _Router_Route_Handler,
		},
		{
			MethodName: "RegisterNode",
			Handler:    _Router_RegisterNode_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _Router_ListNodes_Handler,
		},
		{
			MethodName: "Rebalance",
			Handler:    _Router_Rebalance_Handler,
		},
		{
			MethodName: "StartMigration",
			Handler:    _Router_StartMigration_Handler,
		},
		{
			MethodName: "MigrationProgress",
			Handler:    _Router_MigrationProgress_Handler,
		},
		{
			MethodName: "CommitSwitch",
			Handler:    _Router_CommitSwitch_Handler,
		},
		{
			MethodName: "AbortMigration",
			Handler:    _Router_AbortMigration_Handler,
		},
		{
			MethodName: "RetryMigration",
			Handler:    _Router_RetryMigration_Handler,
		},
		{
			MethodName: "RetireOldRing",
			Handler:    _Router_RetireOldRing_Handler,
		},
		{
			MethodName: "KeyDistribution",
			Handler:    _Router_KeyDistribution_Handler,
		},
		{
			MethodName: "HotStats",
			Handler:    _Router_HotStats_Handler,
		},
		{
			MethodName: "RingDiff",
			Handler:    _Router_RingDiff_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _Router_Resume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/chaosring.proto",
}
